config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'admin/index'
  get 'admin/update'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  telegram_webhook TelegramWebhookController
  resources :players
  resources :admins, only: %i[index update]
  resources :venues, only: [:index]
  root to: 'auth#show'
end

app/views/admin/index.html.slim
.container.mx-auto.my-8
  h1.text-2xl.font-semibold.mb-4 Admin Requests

  .grid.grid-cols-1.md:grid-cols-2.lg:grid-cols-4.gap-4
    - @admin_requests.each do |admin_request|
      .w-full.p-4
        .bg-white.rounded-lg.overflow-hidden.shadow-lg
          .text-center.py-6
            h2.text-lg.font-semibold = " #{ admin_request.player.name } #{ admin_request.player.surname }"
            p.text-gray-600 = "Telegram ID: #{ admin_request.player.t_id } "
            p.text-gray-600 = "Telegram Nickname: #{ admin_request.player.nickname } "

          .mt-4.flex.justify-center.space-x-4.pb-4
            = link_to 'Accept', admin_update_path(admin_request_id: admin_request.id, accepted: true), class: 'px-4 py-2 bg-green-500 text-white rounded hover:bg-green-600'
            = link_to 'Reject', admin_update_path(admin_request_id: admin_request.id, accepted: false), class: 'px-4 py-2 bg-red-500 text-white rounded hover:bg-red-600'

app/views/admin/update.html.erb
<div>
  <h1 class="font-bold text-4xl">Admin#update</h1>
  <p>Find me in app/views/admin/update.html.erb</p>
</div>