config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'admin/index'
  get 'admin/update'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  telegram_webhook TelegramWebhookController
  resources :players
  resources :admins, only: %i[index update]
  resources :venues, only: [:index]
  root to: 'auth#show'
end

app/models/player.rb
# frozen_string_literal: true

# Player model class. Can act as user, admin and friend instances.
# Frined instance is initiated when registered player creates player
# They are binded by `friend_id`.
class Player < ApplicationRecord
  has_many :games, dependent: :destroy
  has_many :venues, through: :games
  has_one :admin
  validates_uniqueness_of :t_id, allow_blank: true

  scope :not_friends, -> { where(friend_id: nil) }
  scope :game_ordered, -> { includes(:games).order('games.created_at') }

  def self.played_together_with(current_player)
    where(id: current_player.venues.joins(:players).pluck('players.id'))
  end

  def admin?
    admin&.accepted? || admin&.sadmin?
  end

  def fullname
    "#{name} #{surname}"
  end

  def full_tag
    "#{name} #{surname} - #{nickname}"
  end
end

app/controllers/players_controller.rb
# frozen_string_literal: true

# Controller class for players. Only shows associated players to the logged current player.
class PlayersController < ApplicationController
  before_action :set_player, only: %i[edit show update]

  def index
    if params[:venue_id]
      venue = Venue.find(params[:venue_id])
      players = venue.players.not_friends
    else
      players = Player.played_together_with(@current_player).not_friends
    end

    @players = players.order('created_at').paginate(page: params[:page], per_page: 12)
  end

  def destroy
    return unless @player.destroy

    redirect_to players_path
    flash[:alert] = 'Player has been deleted'
  end

  def update
    return unless @player.update(player_params)

    flash[:success] = 'Player has been updated'
    redirect_to players_path(venue_id: params[:venue_id])
  end

  private

  def set_player
    @player = Player.find(params[:id])
  end

  def player_params
    params.require(:player).permit(:name, :surname, :nickname, :rating, :t_id, :friend_id)
  end
end

app/helpers/players_helper.rb
# frozen_string_literal: true

# Helper module for Player class
module PlayersHelper
end

app/views/players/_form.html.slim
section.bg-gray-100
  .mx-auto.max-w-screen-xl.px-4.py-16.sm:px-6.lg:px-8
    .grid.grid-cols-1.gap-x-16.gap-y-8.lg:grid-cols-2
      .rounded-lg.bg-white.p-8.shadow-lg
        h2.text-2xl.font-bold.mb-4 Edit Player

        = form_with model: player,url: player_path(id: player.id, venue_id: params[:venue_id]), method: :patch, local: true, html: { class: "space-y-4" } do |f|
          div.grid.grid-cols-2.gap-4
            div
              = f.label :name, class: "block font-medium text-gray-700"
              = f.text_field :name, class: "w-full rounded-lg border-gray-200 p-3 text-sm"

            div
              = f.label :surname, class: "block font-medium text-gray-700"
              = f.text_field :surname, class: "w-full rounded-lg border-gray-200 p-3 text-sm"

          div.grid.grid-cols-2.gap-4
            div
              = f.label :rating, class: "block font-medium text-gray-700"
              = f.number_field :rating, step: 0.1, class: "w-full rounded-lg border-gray-200 p-3 text-sm"
            div
              = f.label :tag, class: "block font-medium text-gray-700"
              = f.text_field :nickname, class: "w-full rounded-lg border-gray-200 p-3 text-sm"

          div.mt-4
            = f.submit "Save Changes", class: "inline-block w-full rounded-lg bg-blue-600 px-5 py-3 font-medium text-white hover:bg-blue-500"
      .rounded-lg.bg-white.p-8.shadow-lg
        h2.text-2xl.font-bold.mb-4 Group Info

app/views/players/edit.html.slim
= render partial: "form", locals: { player: @player }

app/views/players/index.html.slim
div.justify-stretch
	div.flex.flex-col
	  div.overflow-x-auto.sm:-mx-6.lg:-mx-8
	    div.inline-block.min-w-full.py-2.sm:px-6.lg:px-8
	      div.overflow-hidden
	        table.min-w-full.border.text-center.text-sm.font-light.dark:border-neutral-500
	          thead.border-b.font-medium.dark:border-neutral-500
	            tr
	              th.border-r.px-6.py-4.dark:border-neutral-500 #
	              th.border-r.px-6.py-4.dark:border-neutral-500 First
	              th.border-r.px-6.py-4.dark:border-neutral-500 Last
	              th.border-r.px-6.py-4 Tag
	              th.border-r.px-6.py-4 Rating
	              th.px-6.py-4 Actions

	          tbody
	          -@players.each.with_index(@players.offset + 1) do |player, i| 
	            tr.border-b.dark:border-neutral-500
	              td.whitespace-nowrap.border-r.px-6.py-4.font-medium.dark:border-neutral-500= i
	              td.whitespace-nowrap.border-r.px-6.py-4.dark:border-neutral-500= player.name
	              td.whitespace-nowrap.border-r.px-6.py-4.dark:border-neutral-500= player.surname
	              td.border-r.whitespace-nowrap.px-6.py-4= player.nickname
	              td.border-r.whitespace-nowrap.px-6.py-4= player.rating
	              td.whitespace-nowrap.px-6.py-4
	              	button[class="#{dark_btn}"] = link_to "Edit", edit_player_path(id: player.id, venue_id: params[:venue_id])
	              	button[class="#{dark_btn}"] = link_to "Info", player_path(player)
	              	button[class="#{dark_btn}"] = link_to "Delete", player_path(player), data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' }

div.py-4 = will_paginate @players, page_links: false