config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'admin/index'
  get 'admin/update'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  telegram_webhook TelegramWebhookController
  resources :players
  resources :admins, only: %i[index update]
  resources :venues, only: [:index]
  root to: 'auth#show'
end

app/views/layouts/_flash.html.erb
<% if flash.any? %>
  <% flash.each do |type, msg| %>
    <div class="py-2 px-4 font-bold msg-<%= type %>">
      <%= msg %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_header.html.erb
<nav class="bg-blue-600 p-4 text-white">
	<div class="container mx-auto px-8">
		<div class="flex">
			<%= link_to "Team Sorter", venues_path, class: "text-xl font-semibold pr-6" %>
			<ul class="flex space-x-4">
				<li><%= link_to "Players", players_path %></li>
				<li><%= link_to "Admins", admin_index_path %></li>
				<li><%= link_to "Venues", venues_path %></li>
			</ul>
			<div class="flex ml-auto pr-12">
				<%= link_to @current_player.fullname, edit_player_path(@current_player) %>
			</div>
		</div>
	</div>
</nav>

app/views/layouts/_registration.html.slim
section.bg-gray-100
  .mx-auto.max-w-lg.px-4.py-24.sm:px-6.lg:px-8.content-center
    .rounded-lg.bg-white.p-8.shadow-lg
      h2.text-2xl.font-bold.mb-4 1. Go to #{link_to 'Team Sorter Bot', "https://t.me/#{ENV['BOT_NAME']}", class: 'text-blue-700'}
      h2.text-2xl.font-bold.mb-4 2. Request to /become_admin 
      h2.text-2xl.font-bold.mb-4 3. /login again through Telegram

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TeamSorter</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_importmap_tags %>
</head>
<body class="bg-gray-100">
  <% if @current_player&.admin? %>
    <%= render "layouts/header" %>
    <%= render "layouts/flash" %>
    <main class="container mx-auto mt-5 px-5">
      <%= yield %>
    </main>
  <% else %>
    <%= render "layouts/flash" %>
    <%= render "layouts/registration" %>
  <% end -%>
</body>
</html>